apiVersion: v1
data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
kind: Secret
metadata:
  name: sidmlbackend
  namespace: ml-app
---
apiVersion: v1
data:
  functions.main.default: NE9NMjh5Mnd0QmEyQ3JHZjRjZ1JsZ2VMYXUvUFBmbDBNbTlmTWd6OGV0b0x0b09oWFQycER3PT0=
  host.function.default: ZHJCbUJYak4yd05kWnpYYUR3d051TXRtZ0N0WlZEa1cwVVVvaXR0RVQ5Um1EQjNHYXk1YVZRPT0=
  host.master: VDFyMUZERGxROEF3eTQxUHBJalhJMm9kYVl3SDVsTHA5Z2pOMmc4L2EvUnBHc3cyelhySUFRPT0=
  host.systemKey.default: UWFSaTlRU3dQQU9hakpud1p5MHY4WlNSUFFqVW1iMFo5OEhTMC9OTzFqMmRsV3NsL25wZjJBPT0=
kind: Secret
metadata:
  name: func-keys-kube-secret-sidmlbackend
  namespace: ml-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidmlbackend-function-keys-identity-svc-act
  namespace: ml-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: ml-app
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidmlbackend-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: ml-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: sidmlbackend-function-keys-identity-svc-act
---
apiVersion: v1
kind: Service
metadata:
  name: sidmlbackend-http
  namespace: ml-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sidmlbackend-http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidmlbackend-http
  name: sidmlbackend-http
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidmlbackend-http
  template:
    metadata:
      labels:
        app: sidmlbackend-http
    spec:
      containers:
      - env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: twolvlImp
        envFrom:
        - secretRef:
            name: sidmlbackend
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        name: sidmlbackend-http
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 1500m
            memory: 3000Mi
          requests:
            cpu: 800m
            memory: 1500Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /mnt/azure/datasets
          name: azure
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
      volumes:
      - csi:
          driver: blob.csi.azure.com
          volumeAttributes:
            containerName: datasets
            mountOptions: -o allow_other --file-cache-timeout-in-seconds=120
            secretName: azure-secret
        name: azure
