apiVersion: v1
data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
kind: Secret
metadata:
  name: sidmlbackend
  namespace: ml-app
---
apiVersion: v1
data:
  functions.main.default: cmN0YXVzNVd0QmZhak9JMUdBTEtMcnVIeGN1REFmT2JCdTZYa1JkVXI2WUlnTWhBQVRGR0xBPT0=
  host.function.default: OHpzSG9VTWVNU2g4TE9ZSDJ6YmNoenFndkVENEJacmJCNUZnbUkvQWdiVG9VV2czVlhCcXdnPT0=
  host.master: bTVNd00zT2dnTGNCbUxoRlZ2VWhmWDZBV21BM1o1Njh2blhldFE3QzJVMWRJN1VNbWhrcEZnPT0=
  host.systemKey.default: cTYzUU5tbHJOUGZtdTZzUEtaNVRhZmRhZXdDbWRWZ1dON2lTMW5PelQyOHNhQjVENDliYW9nPT0=
kind: Secret
metadata:
  name: func-keys-kube-secret-sidmlbackend
  namespace: ml-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidmlbackend-function-keys-identity-svc-act
  namespace: ml-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: ml-app
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidmlbackend-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: ml-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: sidmlbackend-function-keys-identity-svc-act
---
apiVersion: v1
kind: Service
metadata:
  name: sidmlbackend-http
  namespace: ml-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sidmlbackend-http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidmlbackend-http
  name: sidmlbackend-http
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidmlbackend-http
  template:
    metadata:
      labels:
        app: sidmlbackend-http
    spec:
      containers:
      - env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: twolvlImp
        envFrom:
        - secretRef:
            name: sidmlbackend
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        name: sidmlbackend-http
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 800m
            memory: 2048Mi
          requests:
            cpu: 300m
            memory: 1024Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /mnt/azure/datasets
          name: azure
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
      volumes:
      - csi:
          driver: blob.csi.azure.com
          volumeAttributes:
            containerName: datasets
            mountOptions: -o allow_other --file-cache-timeout-in-seconds=120
            secretName: azure-secret
        name: azure
