apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-sidmlbackend-http
  namespace: ml-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sidmlbackend-http
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
---