data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: ''
apiVersion: v1
kind: Secret
metadata:
  name: mlbackend
---
data:
  host.master: OVhWTG1ocWZXZ2dpRS84d2prMUUyb3dyLzM3OUhEZDFUU2JVaWFza2Fsc2RkN01yV1lIU2pBPT0=
  host.function.default: U0tlY3RoeHoyaVVKQTF6R0RtZ2Nab2F0b2ZheWlmYmVSZjViUlFNa3QycXU0ZjV3S05YUDlnPT0=
  host.systemKey.default: T3EzMXdVTW9RT3ovMFpJeVpYaVJyZmV0bGcvRnVxdG9SMnI4a1lFZmxGUnFpMklhcGJadTF3PT0=
  functions.main.default: VGtDdnczdUZtQWJJQmtRcFU5M29oYUJSZ1MwbEFFQ3FkOFdBa0Z5YndhM1h5N3lhWnRpV05nPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-mlbackend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlbackend-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: mlbackend-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlbackend-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: mlbackend-http
spec:
  selector:
    app: mlbackend-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlbackend-http
  labels:
    app: mlbackend-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbackend-http
  template:
    metadata:
      labels:
        app: mlbackend-http
    spec:
      containers:
      - name: mlbackend-http
        image: mlbackendacr.azurecr.io/core:latest
        volumeMounts:
          - name: azure
            mountPath: /mnt/azure
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-mlbackend
        envFrom:
        - secretRef:
            name: mlbackend
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP

      serviceAccountName: mlbackend-function-keys-identity-svc-act
      volumes:
        - name: azure
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              secretName: azure-secret
              shareName: aksshare
              mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mlbackend-http
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlbackend-http
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
