data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: ''
apiVersion: v1
kind: Secret
metadata:
  name: sidmlbackend
---
data:
  host.master: TjNueXJ4d3d4N09XTGoxa3ZESEdUZEpGNkE2R0YwNlJnUnZ3RlZqaWNHWGdTYndTWTZCSEt3PT0=
  host.function.default: RnBZVkh0L2FzanVzQUEzbUN5cFdoNEFvaVJyT1pwTGZHZzZWMjlRZmltcjRrZklmZ0NRdHJRPT0=
  host.systemKey.default: TnhUaWVOTjd6QTlPdS9ueE1wdkpCeVFGbUhRZWMzd201UXpSdXJJZFgzbUxZQlFpYktOQ2hnPT0=
  functions.main.default: WFlvR29KVzN3V251M0FBMlhhMWJWVHJmNWFydlFwNnhlYS9UNFluYjVkallkSi81bTIvYmt3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-sidmlbackend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidmlbackend-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: sidmlbackend-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidmlbackend-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: sidmlbackend-http
spec:
  type: ClusterIP
  selector:
    app: sidmlbackend-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidmlbackend-http
  labels:
    app: sidmlbackend-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidmlbackend-http
  template:
    metadata:
      labels:
        app: sidmlbackend-http
    spec:
      containers:
      - name: sidmlbackend-http
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        resources:
          limits:
            cpu: 300m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
          - name: azure
            mountPath: /mnt/azure
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: imputation
        envFrom:
        - secretRef:
            name: sidmlbackend
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
      volumes:
        - name: azure
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              secretName: azure-secret
              shareName: aksshare
              mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-sidmlbackend-http
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sidmlbackend-http
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapi-http
spec:
  type: ClusterIP
  selector:
    app: sampleapi-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi-http
  labels:
    app: sampleapi-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi-http
  template:
    metadata:
      labels:
        app: sampleapi-http
    spec:
      containers:
      - name: sampleapi-http
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: sampleapi
        envFrom:
        - secretRef:
            name: sidmlbackend
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
---
