data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: ''
apiVersion: v1
kind: Secret
metadata:
  name: sidmlbackend
  namespace: ml-app
---
data:
  host.master: RmFTTGdxdUJFYzdoTkF4VFNORUZISWNLZWNDMWw5dTRkYUZYR2ZGREVaTTU3eDVwVE5YVXpRPT0=
  host.function.default: RjFNek9XdTZTcHIvc2tDL0RrRFZDZ28vUmZnOVpRUnJPS0x0bVZGZ1dLZTBWQjJkaDRoclpRPT0=
  host.systemKey.default: SWwxczY2b0RHSGtoaDhpZzVtOFIyTEZEZnJJNHFncEcyRDJ3Y1VEb1FLc05YNXhXRzZzMGJRPT0=
  functions.main.default: MnN2dnU5R08wTFJEczBtaGVYNU8wcG84NkJuT1U2SlBPN1dUZjR1Y3ZrTkZNUWIzTmM4TVh3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-sidmlbackend
  namespace: ml-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidmlbackend-function-keys-identity-svc-act
  namespace: ml-app
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: ml-app
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: sidmlbackend-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidmlbackend-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: ml-app
---
apiVersion: v1
kind: Service
metadata:
  name: sidmlbackend-http
  namespace: ml-app
spec:
  selector:
    app: sidmlbackend-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidmlbackend-http
  namespace: ml-app
  labels:
    app: sidmlbackend-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidmlbackend-http
  template:
    metadata:
      labels:
        app: sidmlbackend-http
    spec:
      containers:
      - name: sidmlbackend-http
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        resources:
          limits:
            cpu: 800m
            memory: 2048Mi
          requests:
            cpu: 300m
            memory: 1024Mi
        volumeMounts:
          - name: azure
            mountPath: /mnt/azure/dataset
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: twolvlImp
        envFrom:
        - secretRef:
            name: sidmlbackend
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
      volumes:
        - name: azure
          csi:
            driver: blob.csi.azure.com
            volumeAttributes:
              secretName: azure-secret
              containerName: datasets
              mountOptions: "-o allow_other --file-cache-timeout-in-seconds=120"
---

