apiVersion: v1
kind: Service
metadata:
  name: sampleapi-service
  namespace: ml-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sampleapi-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sampleapi-service
  name: sampleapi-service
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi-service
  template:
    metadata:
      labels:
        app: sampleapi-service
    spec:
      containers:
      - env:
        - name: AzureFunctionsJobHost__functions__0
          value: main
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-sidmlbackend
        - name: MODEL_SERVICE
          value: sampleapi
        envFrom:
        - secretRef:
            name: sidmlbackend
        image: acrmlbackend.azurecr.io/sidmlbackend:latest
        name: sampleapi-service
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
      serviceAccountName: sidmlbackend-function-keys-identity-svc-act
